### 尝试完成登录流程
```
import {take, call, put} from 'redux-saga/effects'

function* authorize(user, password) {
  try {
    const token = yield call(Api.authorize, user, password);
    yield put({type: 'LOGIN_SUCCESS', token})
    return token;
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error})
  }
}

function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUET');
    const token = yield call(authorize, user, password);
    if(token) {
      yield call(Api.storeItem({token}));
      yield take('LOGOUT');
      yield call(Api.cleatItem('token'));
    }
  }
}
```

### 问题:
- 假设loginFlow正在等待call(authorize）被resolve,用户点击了logout按钮使得LOGOUT 的action被发起。因为loginFlow在authorize中被阻塞了，最终发生在开始调用和收到响应之间的LOGOUT将被错过，因为那时logFlow 还没有执行yield take('LOGOUT');
- 上面代码的问题是 call是一个会阻塞的Effect,既Generator在调用结束之前不能执行或者处理其他的任何事情。所以我们需要非阻塞的调用authorize方法。这样loginFlow可以继续执行。并且监听并发或者响应未完成之前发出的LOGOUT的action。
- fork 表示无阻塞的调用。当我们fork一个任务，任务会在后台启动，调用者也可以继续它自己的流程，而不用等待被fork任务结束。
- 但是现在问题是使用fork让authorize的action在后台启动后,我们无法获取token 的结果(因为是非阻塞的)。所以我们需要将token 存储操作移到authorize内部
```
import { fork, call, take, put } from 'redux-saga/effects'

function* authorize(user, password) {
  try{
    const token = yield call(Api.authorize, user, password);
    yield put({type: 'LOGIN_SUCCESS', token});
    yield call(Api.storeItem, {token}); //存储放在内部
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error});
  }
}

function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST');
    yield fork(authorize, user, password);
    yield take(['LOGOUT', 'LOGIN_ERROR']);
    yield call(Api.clearItem, 'token');
  }
}
```
使用 yield take(['LOGOUT','LOGINT_ERROR']),代表监听2个并发的action。
如果我们在Api调用期间收到一个LOGOUT action,我们必须要取消authorize处理进程，否则将有2个并发任务，并且authorize任务辉继续进行，并在成功的响应(或者失败响应)。导致状态不一致。

- 为了取消fork任务，我们可以使用一个指定的Effect cancel。
```
import { take, put, call, fork, cancel } from 'redux-saga/effects'

// ...
function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST');

    const task = yield fork(authorize, user, password);
    const action = yield take(['LOGOUT','LOGIN_ERROR']);

    if(action.type === 'LOGOUT') {
      yield cancel(task);
    }
    yield call(Api.clearItem('token'));
  }
}
```
yield  fork返回结果是一个Task对象，将task传递给cancel的Effect。如果任务还在进行，它会被中止。如果任务已经完成，则什么也不会做。

- 假设在我们收到一个LOGIN_REQUEST  action时，我们在reducer中设置了一些isLoading标示为true,以便界面显示loading效果。如果此时我们Api调用期间收到一个LOGOUT的action,并且通过"杀死它"，终止任务。那状态可能不一致了，isLoading无法变成false;

- cancel Effect不会粗暴的结束我们的authorize任务，他会抛出一个特殊的错误给authorize一个机会执行自己的清理逻辑，而被取消的任务应该捕捉这个错误，假设它需要在结束之前处理一些事情的话。
```
import { isCancelError } from 'redux-saga'

function* authorize(user, password) {
  try {
    const token = yield call(Api.authorize, user, password);
    yield put({type: 'LOGIN_SUCCESS', token});
    return token
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error});
  } finally {
    if(yield cancelled()) {
      yield put({type: 'LOGIN_ERROR', error});
    }
  }
}
```
